[build]
  command = "git submodule update --init --recursive && sudo apt-get install -y graphviz && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PYTHON_VERSION = "3.12"
  NEXT_TELEMETRY_DISABLED = "1"
